chore: Add Mailgun send email action
firebase/firebase-admin-node pull request #1210
Opened 2021-03-29 22:13 UTC by lahirumaramba

- Add GitHub Action to send email using `mailgun.js` npm module.

2021-03-30 21:27 UTC, lahirumaramba commented on .github/actions/send-email/index.js
> +  const cc = core.getInput('cc');
We probably do not need `cc` filed. I am open to remove it and keep this action as simple as possible if we need.

2021-03-30 22:37 UTC, hiranya911 requested changes
Looks pretty good. A few thoughts for improvement.

2021-03-30 22:37 UTC, hiranya911 commented on .github/actions/send-email/index.js
> +function validate() {
Validate all required parameters here. I'd expect more or less everything except cc is required.

2021-03-30 22:37 UTC, hiranya911 commented on .github/actions/send-email/index.js
> +sendEmail();
I'd prefer something like:

```js
const config = loadConfig();
validate(config);
sendEmail(config);
```

2021-03-30 22:37 UTC, hiranya911 commented on .github/workflows/nightly.yml
> +          <a href="github.com/${{github.repository}}/actions/workflows/nightly.yml">failed workflow</a>.
Let's link to https://github.com/firebase/firebase-admin-node/actions. Both here and below.

2021-03-31 18:05 UTC, lahirumaramba commented
Thanks, @hiranya911!
Used a bit of a lazy approach to validate all the required fields. Kept `cc`, `text`, `html`, as optional. If `html` is provided and not `text` the API extracts the text content from the `html`. Let me know what you think.

2021-03-31 19:38 UTC, hiranya911 requested changes
Just a couple of readability nits. And remember to update the binary every time you push a code change.

2021-03-31 19:38 UTC, hiranya911 commented on .github/actions/send-email/index.js
> +    if (['cc', 'text', 'html'].includes(param)) {
```
const optionalFields = ['cc', 'text', 'html'];
```

2021-03-31 19:38 UTC, hiranya911 commented on .github/actions/send-email/index.js
> +function validateParameter(value, name) {
validateRequiredParameter

2021-03-31 20:53 UTC, lahirumaramba commented
Thanks @hiranya911! Updated the binary.

2021-03-31 22:14 UTC, hiranya911 approved these changes
LGTM 👍

2021-03-31 22:22 UTC, merged

2021-04-06 06:54 UTC, decodedfile commented
Duplicate of #