Fix storage emulator env formatting
firebase/firebase-admin-node pull request #1257
Opened 2021-05-07 20:37 UTC by abeisgoat

The Firebase style env var for storage emulator can't have protocol and the Cloud version *must* have a protocol.

2021-05-08 04:00 UTC, hiranya911 requested changes
Change looks good. Need a minor fix in the test case.

2021-05-08 04:00 UTC, hiranya911 commented on test/unit/storage/storage.spec.ts
> +    it('throws if FIREBASE_STORAGE_EMULATOR_HOST has a protocol', () => {
This test is currently passing by accident. There's nowhere in this test that we have set an env variable with the `http://` prefix. If you update the assertion as follows the error surfaces immediately:

```js
expect(() => new Storage(mockApp)).to.throw(
  'FIREBASE_STORAGE_EMULATOR_HOST should not contain a protocol');
```

2021-05-10 17:05 UTC, abeisgoat commented
All fixed, feel free to approve and merge!

2021-05-10 17:15 UTC, hiranya911 approved these changes

2021-05-10 17:15 UTC, lahirumaramba approved these changes
LGTM! Thank you, @abeisgoat !

2021-05-10 17:23 UTC, merged