fix: Fix impersonated service account parsing exception
firebase/firebase-admin-node pull request #1862
Opened 2022-08-10 16:00 UTC by blue-hope

### Discussion

  * related to #1861 

### Testing

  * test for checking impersonated service account added.

### API Changes

  * no change on public API

2022-08-16 09:49 UTC, blue-hope commented
Can I get any feedback on this? Or discussion on #1861 ?

2022-08-31 00:28 UTC, nathan-stable-auto commented
@blue-hope thanks for the PR!

@lahirumaramba I notice you self-assigned the related issue https://github.com/firebase/firebase-admin-node/issues/1703 - would you be able provide any input on how to move this forward? Thanks very much!

2022-10-04 10:50 UTC, branks approved these changes

2022-10-12 09:11 UTC, blue-hope commented
@lahirumaramba I hope this feature will be dealt with soon and I would be so appreciated if you could give us a feedback or review.

2022-10-18 15:20 UTC, lahirumaramba commented
Thank you everyone for your patience! Hey @blue-hope Thank you so much for the contribution! Just adding this note to let you know that I have started the review process. We also plan to migrate the credentials implementation to `google-auth-library-nodejs` (see https://github.com/firebase/firebase-admin-node/issues/1377) and once that is done firebase-admin will reach feature parity with `google-auth-library-nodejs`. In the meantime, I think it is reasonable to merge this change.

2022-11-13 14:02 UTC, IchordeDionysos commented
@lahirumaramba just a side-note on the migration to `google-auth-library-nodejs`:
Right now, it's possible to do the following using a local service account:

Run: `gcloud auth application-default login` 

```
initializeFirebase({project: 'project'});

getFirestore().doc('foo/bar').get();
```

However, trying to authenticate with Identity Toolkit / Firebase Auth would fail:

```
initializeFirebase({project: 'project'});

getAuth().getUser('uid'); // -> throws an error
```

Would the migration to `google-auth-library-nodejs` library fix this problem?

2022-11-18 20:16 UTC, lahirumaramba requested changes
Hi @blue-hope, Thank you again for your contributions. It looks pretty good overall... I think we can improve the test coverage. Added a few comments and one question. Please take a look. Thanks!

2022-11-18 20:16 UTC, lahirumaramba commented on test/unit/app/credential-internal.spec.ts
> +
Let's add another test to `httpAgent`:

```
  it('ImpersonatedServiceAccountCredential should use the provided HTTP Agent', () => {
    const agent = new Agent();
    const c = new ImpersonatedServiceAccountCredential(MOCK_IMPERSONATED_TOKEN_CONFIG, agent);
    return c.getAccessToken().then((token) => {
      expect(token.access_token).to.equal(expectedToken);
      expect(stub).to.have.been.calledOnce;
      expect(stub.args[0][0].httpAgent).to.equal(agent);
    });
  });
```

2022-11-18 20:16 UTC, lahirumaramba commented on test/unit/app/credential-internal.spec.ts
> +
Actually, I think we can improve the test coverage for `ImpersonatedServiceAccountCredential`. Please see `describe('RefreshTokenCredential', () => {` for an example.

Let's also add another test in `describe('isApplicationDefault()', () => {`

```
  it('should return true for ImpersonatedServiceAccountCredential loaded from GOOGLE_APPLICATION_CREDENTIALS', () => {
    process.env.GOOGLE_APPLICATION_CREDENTIALS = path.resolve(__dirname, '../../resources/mock.impersonated_key.json');
    const c = getApplicationDefault();
    expect(c).is.instanceOf(ImpersonatedServiceAccountCredential);
    expect(isApplicationDefault(c)).to.be.true;
  });

 it('should return false for explicitly loaded ImpersonatedServiceAccountCredential', () => {
    const c = new ImpersonatedServiceAccountCredential(mockImpersonatedAccount);
    expect(isApplicationDefault(c)).to.be.false;
  });
```

2022-11-18 20:19 UTC, lahirumaramba commented
> Thank you so much for reviewing. (+ Just curious, when will that `google-auth-library-nodejs` implementation be finished?)

I can't promise a timeline for this, but we are starting the initial work this year. It will be a but complex migration so we plan to perform it in multiple stages. We will use #1377 to track any progress.

2022-11-18 20:24 UTC, lahirumaramba commented
> @lahirumaramba just a side-note on the migration to `google-auth-library-nodejs`: Right now, it's possible to do the following using a local service account:
> 
> Run: `gcloud auth application-default login`
> 
> ```
> initializeFirebase({project: 'project'});
> 
> getFirestore().doc('foo/bar').get();
> ```
> 
> However, trying to authenticate with Identity Toolkit / Firebase Auth would fail:
> 
> ```
> initializeFirebase({project: 'project'});
> 
> getAuth().getUser('uid'); // -> throws an error
> ```
> 
> Would the migration to `google-auth-library-nodejs` library fix this problem?

Hi @IchordeDionysos, This looks a bit strange. `gcloud auth application-default login` should set `GCLOUD_CREDENTIAL_PATH` and load ADC. If this is reproducible, please file a new issue with a code sample and any error logs. Thanks!

2022-11-19 12:33 UTC, blue-hope commented on src/app/credential-internal.ts
> +  const credentialsFile = readCredentialFile(filePath, ignoreMissing);
Sure, so I passed `ignoreMissing` as false when check `GOOGLE_APPLICATION_CREDENTIALS` on line 486. So we still can encounter `FirebaseAppError` when an incorrect file path is passed.

2022-11-19 12:33 UTC, blue-hope commented on test/resources/mock.impersonated_key.json
> +  }
Thanks!

2022-11-21 22:14 UTC, lahirumaramba approved these changes
Thanks for addressing the review feedback! LGTM!
Let me know if you can add the missing unit tests. As an alternative, we can merge this as it is and I am happy to add the missing tests in a follow-up PR.

2022-11-22 12:44 UTC, blue-hope commented
@lahirumaramba I'll add missing tests and notice to you before merge, thanks!

2022-11-23 04:41 UTC, blue-hope commented
@lahirumaramba New test added. I missed checking implicit discovered credential, Thanks a lot.

2022-12-01 16:41 UTC, lahirumaramba approved these changes
Thank you @blue-hope! LGTM!

2022-12-21 03:14 UTC, blue-hope commented
@lahirumaramba When this will be released? 😄

2023-01-12 14:29 UTC, Klaitos commented
Definitively need this

2023-01-13 15:51 UTC, merged

2023-01-19 17:44 UTC, lahirumaramba commented
Thank you @blue-hope for your contribution. This feature is now included in the [v11.5.0 release](https://firebase.google.com/support/release-notes/admin/node#11.5.0).

Thanks folks for your patience on this! Try out the new feature if you get a chance and let us know what you think.
If you encounter any issues, please open a new issue on Github. Thank you!