adding optional param to token verifier
firebase/firebase-admin-node pull request #2370
Opened 2023-11-14 18:04 UTC by pragatimodi

2024-01-19 18:26 UTC, Xiaoshouzi-gh approved these changes
LTGM.
Please hold off on the merging before code-freeze lift.

2024-01-19 18:26 UTC, Xiaoshouzi-gh commented on src/auth/token-verifier.ts
> +    } else if (!(payload.event_type !== undefined &&
let's add a comment below this line explain what this is and why we needed it.
You can re-phrase below for reasons - for beforeEmailSend and beforeSMSSend events, there is no user record available.  sub is the same as uid which is part of the user record.

2024-01-19 18:27 UTC, Xiaoshouzi-gh requested changes
are you able to add unit tests for this?

2024-03-18 22:13 UTC, Xiaoshouzi-gh approved these changes
Awesome LGTM

2024-03-26 20:14 UTC, lahirumaramba approved these changes
LGTM! Thank you!

2024-04-15 22:34 UTC, merged